# Generated by Django 3.0.6 on 2020-05-26 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200525_0949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knjigaizdanje',
            options={'ordering': ['vracanje'], 'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
    ]
