# Generated by Django 3.0.6 on 2020-05-26 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200526_1152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knjigaizdanje',
            options={'ordering': ['vracanje'], 'permissions': (('obnova', 'obnoviti'),)},
        ),
    ]
