# Generated by Django 3.0.6 on 2020-06-03 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200527_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=100)),
                ('prezime', models.CharField(max_length=100)),
                ('god_rodjenja', models.DateField(blank=True, null=True, verbose_name='rodjen')),
                ('god_smrti', models.DateField(blank=True, null=True, verbose_name='umro')),
            ],
            options={
                'ordering': ['prezime', 'ime'],
            },
        ),
        migrations.CreateModel(
            name='Zanr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='knjiga',
            name='zanr',
            field=models.ManyToManyField(help_text='odabrati žanr', to='app.Zanr'),
        ),
        migrations.AlterField(
            model_name='knjiga',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Autor'),
        ),
    ]
