# Generated by Django 3.0.6 on 2020-06-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200603_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knjiga',
            name='zanr',
            field=models.ManyToManyField(to='app.Zanr'),
        ),
    ]
