# Generated by Django 3.0.6 on 2020-06-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200603_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='god_rodjenja',
            field=models.DateField(blank=True, null=True, verbose_name='Godina rođenja'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='god_smrti',
            field=models.DateField(blank=True, null=True, verbose_name='Godina smrti'),
        ),
    ]
