# Generated by Django 3.0.6 on 2020-06-04 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20200604_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knjiga',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Autor'),
        ),
    ]
