# Generated by Django 3.0.6 on 2020-05-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Knjiga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=30)),
                ('izdavacka_kuca', models.CharField(max_length=50)),
                ('godina_izdanja', models.DateField()),
                ('status', models.IntegerField()),
            ],
        ),
    ]
