# Generated by Django 3.0.6 on 2020-05-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knjiga',
            name='naziv',
            field=models.CharField(max_length=60),
        ),
    ]
