# Generated by Django 3.0.6 on 2020-05-25 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_knjigaizdanje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knjiga',
            name='status',
        ),
        migrations.AddField(
            model_name='knjigaizdanje',
            name='posudjivac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='knjigaizdanje',
            name='status',
            field=models.CharField(blank=True, choices=[('u', 'U pripravnosti'), ('p', 'Posudjena'), ('d', 'Dostupna'), ('r', 'Rezervirana')], default='u', help_text='Dostupnost knjige', max_length=1),
        ),
    ]
