# Generated by Django 3.0.6 on 2020-05-26 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200526_1145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knjigaizdanje',
            options={'ordering': ['vracanje']},
        ),
    ]
