# Generated by Django 3.0.6 on 2020-05-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200526_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knjigaizdanje',
            name='status',
            field=models.CharField(blank=True, choices=[('u', 'U pripravnosti'), ('p', 'Posudjena'), ('d', 'Dostupna'), ('r', 'Rezervirana')], default='u', max_length=1),
        ),
    ]
