# Generated by Django 3.0.6 on 2020-06-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200603_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knjiga',
            name='autor',
            field=models.CharField(max_length=60),
        ),
    ]
