# Generated by Django 3.0.6 on 2020-06-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200603_1238'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Autor',
        ),
        migrations.RemoveField(
            model_name='knjiga',
            name='zanr',
        ),
        migrations.AlterField(
            model_name='knjiga',
            name='autor',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='Zanr',
        ),
    ]
