# Generated by Django 3.0.6 on 2020-06-04 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200603_1303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'ordering': ['prezime', 'ime'], 'verbose_name_plural': 'Autori'},
        ),
        migrations.AlterModelOptions(
            name='knjiga',
            options={'verbose_name_plural': 'Knjige'},
        ),
        migrations.AlterModelOptions(
            name='knjigaizdanje',
            options={'ordering': ['vracanje'], 'permissions': (('obnova', 'obnoviti'),), 'verbose_name_plural': 'Izdanja knjiga'},
        ),
        migrations.AlterModelOptions(
            name='zanr',
            options={'verbose_name_plural': 'Žanrovi'},
        ),
    ]
