# Generated by Django 3.0.6 on 2020-06-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20200604_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knjiga',
            name='zanr',
            field=models.ManyToManyField(to='app.Zanr', verbose_name='Žanr'),
        ),
    ]
