# Generated by Django 3.0.6 on 2020-06-04 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0019_auto_20200604_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knjigaizdanje',
            name='posudjivac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Posuđivač'),
        ),
    ]
