# Generated by Django 3.0.6 on 2020-06-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20200604_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knjigaizdanje',
            name='status',
            field=models.CharField(blank=True, choices=[('p', 'Posuđena'), ('d', 'Dostupna')], default='d', max_length=1),
        ),
    ]
